baseURL: https://william-byun-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for William Byun
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Data Analytics at LBS
    title: Welcome to William Byun's website
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Rochester Row
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: wbyun.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7411-564-197 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: William Byun
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
         #label: Twitter
        # url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/william.byun.1
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/will_byuny/
      - icon: fa-github
        label: GitHub
        url: https://github.com/willbyun1201/my_website
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/william-young-hwan-byun-1201/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
       # url: elements.html
    menu: Menu
    subtitle: By William Byun
    title: My Portfolio
  tiles:
    enable: yes
    showcase:
      - image: william.jpg
        subtitle: A short biography
        title: About me
        url: blogs/About_me
      - image: wallstreet.jpeg
        subtitle: Analysis
        title: Risk Return of DIJA Industrial Average
        url: blogs/risk_return
      - image: airbnb.jpg
        subtitle: Berlin Airbnb Analysis
        title: Group 5 Project
        url: blogs/Air_BnB
      - image: lbs.jpg
        subtitle: My CV
        title: Resume
        url: '/files/William_Young_Hwan_Byun_CV.pdf'
      #- image: pic05.jpg
        #subtitle: Resume
        #title: My CV
        #url: blogs/ipsum
      #- image: pic06.jpg
        #subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Please contact me via 'send a message' below, email, phone or social media!"
    title: William Byun
    url: blogs
